export interface IArticle {
    sku: string,
    name: string,
    salePrice: number,
    regularPrice: number,
    thumbnailImage: string,
    shortDescription: string,
    highResImage: string
}

export const articlesGlobeaux = [
    {
        "sku": "14611307",
        "name": "Moniteur jeu DEL incurvé VA HD int. GTG 4 ms FreeSync 75 Hz 32 po Samsung (LC32R500)-Bleu gris foncé",
        "shortDescription": "Conçu pour offrir des expériences de jeu immersives, ce moniteur de jeu FreeSync de 32 po de Samsung est doté d'un écran incurvé 1500R avec résolution HD intégrale 1920 x 1080, pour des images cristallines. Son temps de réponse gris à gris de 4 ms, son taux de rafraîchissement de 75 Hz et la technologie Radeon FreeSync d'AMD assurent l'exécution fluide et sans décalage des jeux rapides, sans décalage ou saccade.",
        "customerRating": 4.08,
        "customerRatingCount": 49,
        "customerReviewCount": 49,
        "productUrl": "/fr-ca/produit/moniteur-jeu-del-incurve-va-hd-int-gtg-4-ms-freesync-75-hz-32-po-samsung-lc32r500-bleu-gris-fonce/14611307",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 379.99,
        "salePrice": 279.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/146/14611/14611307.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 6.0,
        "seoText": "moniteur-jeu-del-incurve-va-hd-int-gtg-4-ms-freesync-75-hz-32-po-samsung-lc32r500-bleu-gris-fonce",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/146/14611/14611307.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": true,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "14933347",
        "name": "Moniteur jeu FreeSync DEL IPS FHD 75 Hz 24 po de Samsung/5 ms GTG (LF24T350FHNXZA) - Gris-bleu foncé",
        "shortDescription": "Que ce soit pour travailler, jouer ou vous divertir, vous profiterez d'images et de scènes claires, lumineuses et réalistes à tout coup sur ce moniteur de jeu de 24 po de Samsung. Avec sa résolution HD intégrale et ses angles de visionnement très larges, il vous permet de plonger facilement dans l'action. Sa technologie FreeSync réduit le déchirement d'image pour des mouvements fluides.",
        "customerRating": 4.63,
        "customerRatingCount": 3460,
        "customerReviewCount": 3460,
        "productUrl": "/fr-ca/produit/moniteur-jeu-freesync-del-ips-fhd-75-hz-24-po-de-samsung-5-ms-gtg-lf24t350fhnxza-gris-bleu-fonce/14933347",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 199.99,
        "salePrice": 169.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/149/14933/14933347.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-jeu-freesync-del-ips-fhd-75-hz-24-po-de-samsung-5-ms-gtg-lf24t350fhnxza-gris-bleu-fonce",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/149/14933/14933347.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": true,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "15372257",
        "name": "Moniteur de jeu DEL AV incurvé FHD 1 ms 165 Hz 27 po Optix de MSI (G27C6) - Noir",
        "shortDescription": "Profitez de jeux intenses avec des images claires et fluides grâce au moniteur de jeu à DEL de 27 po Optix de MSI. Son écran incurvé de 27 po avec résolution HD intégrale de 1920 x 1080 offre une expérience de visionnement très immersive, tandis que son temps de réponse de 1 ms et taux de rafraîchissement de 165 Hz assurent des jeux fluides. Son angle de visionnement de 178° vous permet de voir l'écran clairement dans plusieurs angles.",
        "customerRating": 4.45,
        "customerRatingCount": 11,
        "customerReviewCount": 11,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-del-av-incurve-fhd-1-ms-165-hz-27-po-optix-de-msi-g27c6-noir/15372257",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 319.99,
        "salePrice": 319.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/153/15372/15372257.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-de-jeu-del-av-incurve-fhd-1-ms-165-hz-27-po-optix-de-msi-g27c6-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/153/15372/15372257.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "15732100",
        "name": "Moniteur DEL HD intégrale AV GTG 1 ms 75 Hz de 23,8 po d'Acer (KA242Y ABI) - Noir",
        "shortDescription": "Le moniteur de 23,8 po d’Acer est conçu pour vous faire vivre une expérience de visionnement remarquable. Doté d’un panneau à alignement vertical de 23,8 po et d’une résolution HD intégrale, il affiche des détails précis et des couleurs éclatantes dans toutes les scènes. La technologie Flicker-Free avec filtre BlueLight protège vos yeux de la fatigue causée par une exposition prolongée.",
        "customerRating": 4.62,
        "customerRatingCount": 493,
        "customerReviewCount": 493,
        "productUrl": "/fr-ca/produit/moniteur-del-hd-integrale-av-gtg-1-ms-75-hz-de-23-8-po-d-acer-ka242y-abi-noir/15732100",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 199.99,
        "salePrice": 149.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/157/15732/15732100.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-del-hd-integrale-av-gtg-1-ms-75-hz-de-23-8-po-d-acer-ka242y-abi-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/157/15732/15732100.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": true,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "15493199",
        "name": "Moniteur jeu G-Sync DEL HD int. IPS 240 Hz FreeSync GTG 1 ms 27 po UltraGear LG (27GP750-B) - Noir",
        "shortDescription": "Donnez vie à vos jeux préférés avec ce moniteur de jeu DEL IPS UltraGear de LG. Doté d'une résolution HD intégrale 1080p, ce moniteur de 27 po prend en charge le contenu en résolution très immersive HDR10 avec une précision des couleurs maximale, pour des jeux réalistes. Avec le mode de stabilisation des noirs, vous verrez clairement vos ennemis et pourrez les éliminer, même dans les zones les plus sombres.",
        "customerRating": 4.5,
        "customerRatingCount": 14,
        "customerReviewCount": 14,
        "productUrl": "/fr-ca/produit/moniteur-jeu-g-sync-del-hd-int-ips-240-hz-freesync-gtg-1-ms-27-po-ultragear-lg-27gp750-b-noir/15493199",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 499.99,
        "salePrice": 359.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/154/15493/15493199.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-jeu-g-sync-del-hd-int-ips-240-hz-freesync-gtg-1-ms-27-po-ultragear-lg-27gp750-b-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/images/common/pictures/noimage1500x1500.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": true,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "14763270",
        "name": "Moniteur de jeu incurvé DEL HD int. VA FreeSync GTG 1 ms 165 Hz 31,5 po Acer (ED320QR Sbiipx) - Noir",
        "shortDescription": "Branchez votre équipement de jeu à ce moniteur de jeu de 31,5 po d'Acer pour profiter d'une expérience de jeu immersive. Doté d'un écran incurvé élégant de 31,5 po avec résolution HD intégrale de 1920 x 1080, il offre des images exceptionnelles et un vaste champ de vision. Il est également doté d'une technologie d'affichage spéciale pour réduire la fatigue oculaire pendant les longues séances de jeu.",
        "customerRating": 3.94,
        "customerRatingCount": 67,
        "customerReviewCount": 67,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-incurve-del-hd-int-va-freesync-gtg-1-ms-165-hz-31-5-po-acer-ed320qr-sbiipx-noir/14763270",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 399.99,
        "salePrice": 399.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/147/14763/14763270.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 6.0,
        "seoText": "moniteur-de-jeu-incurve-del-hd-int-va-freesync-gtg-1-ms-165-hz-31-5-po-acer-ed320qr-sbiipx-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/147/14763/14763270.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "16233319",
        "name": "Moniteur de jeu HD intégrale ACL VA IPS FreeSync 60 Hz 5 ms gris à gris 22 po de LG (22MP44B-C) - Gris anthracite",
        "shortDescription": "Profitez de vos jeux préférés avec la performance visuelle incroyable offerte par le moniteur de jeu HD intégrale de 22 po de LG. Doté d'une dalle VA de 22 po avec résolution HD intégrale, il représente chaque scène avec des couleurs vives et des détails clairs et nets. Ce moniteur offre aussi des angles de visionnement larges de 178 degrés qui assurent visibilité et clarté, d'où que vous le regardez.",
        "customerRating": 4.67,
        "customerRatingCount": 3,
        "customerReviewCount": 3,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-hd-integrale-acl-va-ips-freesync-60-hz-5-ms-gris-a-gris-22-po-de-lg-22mp44b-c-gris-anthracite/16233319",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 149.99,
        "salePrice": 119.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/162/16233/16233319.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-de-jeu-hd-integrale-acl-va-ips-freesync-60-hz-5-ms-gris-a-gris-22-po-de-lg-22mp44b-c-gris-anthracite",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/images/common/pictures/noimage1500x1500.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": true,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "14933348",
        "name": "Moniteur jeu FreeSync DEL IPS FHD 75 Hz 27 po de Samsung/5 ms GTG (LF27T350FHNXZA) - Gris-bleu foncé",
        "shortDescription": "Que ce soit pour travailler, jouer ou vous divertir, vous profiterez d'images et de scènes claires, lumineuses et réalistes à tout coup sur ce moniteur de jeu de 27 po de Samsung. Avec sa résolution HD intégrale et ses angles de visionnement très larges, il vous permet de plonger facilement dans l'action. Sa technologie FreeSync réduit le déchirement d'image pour des mouvements fluides.",
        "customerRating": 4.62,
        "customerRatingCount": 3434,
        "customerReviewCount": 3434,
        "productUrl": "/fr-ca/produit/moniteur-jeu-freesync-del-ips-fhd-75-hz-27-po-de-samsung-5-ms-gtg-lf27t350fhnxza-gris-bleu-fonce/14933348",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 299.99,
        "salePrice": 299.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/149/14933/14933348.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-jeu-freesync-del-ips-fhd-75-hz-27-po-de-samsung-5-ms-gtg-lf27t350fhnxza-gris-bleu-fonce",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/149/14933/14933348.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "16235322",
        "name": "Moniteur de jeu incurvé DEL HD intégrale FreeSync 1 ms gris à gris 165 Hz 27 po Acer (ED273 PBIIPX) - Noir",
        "shortDescription": "Regardez vos films et vos émissions de télévision prendre vie sur cet incroyable écran de jeu incurvé de 27 po d'Acer. Doté d'une grande dalle DEL HD intégrale, il offre des images spectaculaires avec des noirs profonds et des couleurs éclatantes pour les jeux, les films et plus encore. Cet écran incurvé 16:9 remplit votre vision périphérique pour vous offrir une expérience de visionnement immersive.",
        "customerRating": 3.0,
        "customerRatingCount": 2,
        "customerReviewCount": 2,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-incurve-del-hd-integrale-freesync-1-ms-gris-a-gris-165-hz-27-po-acer-ed273-pbiipx-noir/16235322",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 279.99,
        "salePrice": 219.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/162/16235/16235322.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-de-jeu-incurve-del-hd-integrale-freesync-1-ms-gris-a-gris-165-hz-27-po-acer-ed273-pbiipx-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/162/16235/16235322.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "14933346",
        "name": "Moniteur jeu FreeSync DEL IPS FHD 75 Hz 22 po de Samsung/5 ms GTG (LF22T350FHNXZA) - Gris-bleu foncé",
        "shortDescription": "Que ce soit pour travailler, jouer ou vous divertir, vous profiterez d'images et de scènes claires, lumineuses et réalistes à tout coup sur ce moniteur de jeu de 22 po de Samsung. Avec sa résolution HD intégrale et ses angles de visionnement très larges, il vous permet de plonger facilement dans l'action. Sa technologie FreeSync réduit le déchirement d'image pour des mouvements fluides.",
        "customerRating": 4.64,
        "customerRatingCount": 3414,
        "customerReviewCount": 3414,
        "productUrl": "/fr-ca/produit/moniteur-jeu-freesync-del-ips-fhd-75-hz-22-po-de-samsung-5-ms-gtg-lf22t350fhnxza-gris-bleu-fonce/14933346",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 169.99,
        "salePrice": 169.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/149/14933/14933346.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-jeu-freesync-del-ips-fhd-75-hz-22-po-de-samsung-5-ms-gtg-lf22t350fhnxza-gris-bleu-fonce",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/149/14933/14933346.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "16178128",
        "name": "Moniteur jeu FreeSync DEL incurvé 1000R AV HD intégrale 165 Hz GTG 1 MS 27 po Optix de MSI avec HAS (G271CP)",
        "shortDescription": "Profitez d'images détaillées quand vous jouez avec le moniteur incurvé HD intégrale de 165 Hz et 27 po Optix de MSI. Le temps de réponse de 1 ms minimise le flou, les traînées et les images fantômes pour une expérience de jeu fluide, tandis que la technologie FreeSync d'AMD élimine le décalage pour des images sans saccades ni déchirement. Il est doté d'un support ergonomique avec des réglages pour ajuster l'inclinaison et la hauteur afin que vous puissiez créer une configuration personnalisée, et la compatibilité avec un support VESA vous permet de l'installer au mur.",
        "customerRating": 0.0,
        "customerRatingCount": 0,
        "customerReviewCount": 0,
        "productUrl": "/fr-ca/produit/moniteur-jeu-freesync-del-incurve-1000r-av-hd-integrale-165-hz-gtg-1-ms-27-po-optix-de-msi-avec-has-g271cp/16178128",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 359.99,
        "salePrice": 259.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/161/16178/16178128.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-jeu-freesync-del-incurve-1000r-av-hd-integrale-165-hz-gtg-1-ms-27-po-optix-de-msi-avec-has-g271cp",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/161/16178/16178128.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "14628303",
        "name": "Moniteur jeu DEL incurvé VA HD int. GTG 4 ms FreeSync 75 Hz 32 po Samsung (LC32T550FDNXZA)-Bleu/Gris",
        "shortDescription": "Rehaussez votre expérience de jeu avec le moniteur de jeu incurvé de 32 po de Samsung. Il est doté d'une résolution HD intégrale 1080p avec un écran incurvé 1000R doté de la technologie antiscintillement Anti-Flicker et d'un mode de protection des yeux pour réduire la fatigue oculaire. La technologie FreeSync d'AMD et le temps de réponse de 4 ms minimisent les traînées, le flou et le décalage de l'image dans les séquences de jeu rapides.",
        "customerRating": 4.35,
        "customerRatingCount": 330,
        "customerReviewCount": 330,
        "productUrl": "/fr-ca/produit/moniteur-jeu-del-incurve-va-hd-int-gtg-4-ms-freesync-75-hz-32-po-samsung-lc32t550fdnxza-bleu-gris/14628303",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 349.99,
        "salePrice": 249.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/146/14628/14628303.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 6.0,
        "seoText": "moniteur-jeu-del-incurve-va-hd-int-gtg-4-ms-freesync-75-hz-32-po-samsung-lc32t550fdnxza-bleu-gris",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/146/14628/14628303.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "15262568",
        "name": "Moniteur FreeSync DEL incurvé VA WQHD 165 Hz 34 po Odyssey G5 Samsung/1 ms GTG (LC34G55TWWNXZA)-Noir",
        "shortDescription": "Explorez la totalité du champ de bataille comme jamais auparavant avec le moniteur de jeu DEL VA de 34 po Odyssey G5 de Samsung. Doté d'un très grand écran incurvé 1000R avec résolution WQHD, il affiche chaque moment d'action avec une qualité d'image époustouflante. Avec la technologie HDR10, vous verrez des détails optimisés dans les zones claires et ombragées de votre jeu.",
        "customerRating": 4.45,
        "customerRatingCount": 1284,
        "customerReviewCount": 1284,
        "productUrl": "/fr-ca/produit/moniteur-freesync-del-incurve-va-wqhd-165-hz-34-po-odyssey-g5-samsung-1-ms-gtg-lc34g55twwnxza-noir/15262568",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 699.99,
        "salePrice": 699.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/152/15262/15262568.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 6.0,
        "seoText": "moniteur-freesync-del-incurve-va-wqhd-165-hz-34-po-odyssey-g5-samsung-1-ms-gtg-lc34g55twwnxza-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/152/15262/15262568.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "13819627",
        "name": "Moniteur de jeu DEL FHD TN G-Sync 0.5 ms gris à gris 165 Hz de 24 po d'ASUS (VG248QG) - Noir",
        "shortDescription": "Redécouvrez vos jeux avec ce moniteur de jeu HD intégrale de 24 po d'ASUS. Avec la technologie G-SYNC de NVIDIA, un taux de rafraîchissement ultrarapide de 165 Hz et un temps de réponse de 0,5 ms, il affiche des images très fluides avec des détails réalistes. Il inclut un support ergonomique réglable et intègre la technologie Eye Care d'ASUS pour assurer votre confort durant le visionnement.",
        "customerRating": 4.46,
        "customerRatingCount": 170,
        "customerReviewCount": 170,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-del-fhd-tn-g-sync-0-5-ms-gris-a-gris-165-hz-de-24-po-d-asus-vg248qg-noir/13819627",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 249.99,
        "salePrice": 249.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/138/13819/13819627.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-de-jeu-del-fhd-tn-g-sync-0-5-ms-gris-a-gris-165-hz-de-24-po-d-asus-vg248qg-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/138/13819/13819627.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "15956824",
        "name": "Moniteur de jeu HD intégrale DEL AV FreeSync GTG 1 ms 165 Hz 23,8 po TUF d'ASUS (VG247Q1A)",
        "shortDescription": "Améliorez votre performance de jeu avec le moniteur de jeu HD intégrale FreeSync de 23,8 po TUF d'ASUS. Il a un taux de rafraîchissement ultrarapide de 165 Hz (prend en charge 144 Hz) qui élimine tous les ralentissements et les décalages, pour des jeux fluides. Sa technologie FreeSync minimise le déchirement, pour des mouvements fluides, et la technologie Extreme Low Motion Blur d'ASUS offre un temps de réponse de 1 ms pour des images nettes.",
        "customerRating": 3.5,
        "customerRatingCount": 2,
        "customerReviewCount": 2,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-hd-integrale-del-av-freesync-gtg-1-ms-165-hz-23-8-po-tuf-d-asus-vg247q1a/15956824",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 239.99,
        "salePrice": 239.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/159/15956/15956824.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-de-jeu-hd-integrale-del-av-freesync-gtg-1-ms-165-hz-23-8-po-tuf-d-asus-vg247q1a",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/159/15956/15956824.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "15445753",
        "name": "Moniteur jeu FreeSync DEL IPS HD intégrale GTG 5 ms 75 Hz 27 po de LG (27MP500-B) - Noir",
        "shortDescription": "Jouez mieux que jamais avec le moniteur de jeu de 27 po de LG. Doté d'un écran DEL presque sans cadre à résolution native HD intégrale, il affiche des images claires à couper le souffle dans tous les jeux. Il comprend la technologie Radeon FreeSync pour minimiser le déchirement et les saccades, des taux de rafraîchissement et des temps de réponse exceptionnels ainsi que de multiples entrées pour brancher divers appareils.",
        "customerRating": 4.29,
        "customerRatingCount": 162,
        "customerReviewCount": 162,
        "productUrl": "/fr-ca/produit/moniteur-jeu-freesync-del-ips-hd-integrale-gtg-5-ms-75-hz-27-po-de-lg-27mp500-b-noir/15445753",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 219.99,
        "salePrice": 189.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/154/15445/15445753.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-jeu-freesync-del-ips-hd-integrale-gtg-5-ms-75-hz-27-po-de-lg-27mp500-b-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/154/15445/15445753.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": true,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "14868579",
        "name": "Moniteur jeu FreeSync ACL incurvé VA QHD 165 Hz GTG 1ms 31,5 po TUF d'ASUS (VG32VQ1B)",
        "shortDescription": "Conçu pour les joueurs, ce moniteur TUF de 31,5 po d'ASUS ne manquera pas de rehausser votre expérience de jeu. Il est doté d'un écran incurvé avec résolution QHD, d'un temps de réponse de 1 ms et d'un taux de rafraîchissement de 165 Hz pour une expérience de jeu immersive et fluide. Deux ports HDMI 2.0 et un port DisplayPort 1.2 offrent d'excellentes options de connectivité.",
        "customerRating": 4.08,
        "customerRatingCount": 13,
        "customerReviewCount": 13,
        "productUrl": "/fr-ca/produit/moniteur-jeu-freesync-acl-incurve-va-qhd-165-hz-gtg-1ms-31-5-po-tuf-d-asus-vg32vq1b/14868579",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 479.95,
        "salePrice": 379.97,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/148/14868/14868579.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 6.0,
        "seoText": "moniteur-jeu-freesync-acl-incurve-va-qhd-165-hz-gtg-1ms-31-5-po-tuf-d-asus-vg32vq1b",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/148/14868/14868579.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "16470039",
        "name": "Moniteur de jeu FreeSync ACL VA HD intégrale 60 Hz 22 po de LG avec temps de réponse de 5 ms gris à gris (22MP44B-C) - Gris anthracite - Boîte ouverte",
        "shortDescription": "<p><strong>Produit boîte ouverte certifié Geek Squad. Détails ci-dessous.</strong></p>Profitez de vos jeux préférés avec la performance visuelle incroyable offerte par le moniteur de jeu HD intégrale de 22 po de LG. Doté d'une dalle VA de 22 po avec résolution HD intégrale, il représente chaque scène avec des couleurs vives et des détails clairs et nets. Ce moniteur offre aussi des angles de visionnement larges de 178 degrés qui assurent visibilité et clarté, d'où que vous le regardez.",
        "customerRating": 0.0,
        "customerRatingCount": 0,
        "customerReviewCount": 0,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-freesync-acl-va-hd-integrale-60-hz-22-po-de-lg-avec-temps-de-reponse-de-5-ms-gris-a-gris-22mp44b-c-gris-anthracite-boite-ouverte/16470039",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 144.49,
        "salePrice": 101.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/164/16470/16470039.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-de-jeu-freesync-acl-va-hd-integrale-60-hz-22-po-de-lg-avec-temps-de-reponse-de-5-ms-gris-a-gris-22mp44b-c-gris-anthracite-boite-ouverte",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/images/common/pictures/noimage1500x1500.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "15445751",
        "name": "Moniteur de jeu DEL IPS HD intégrale GTG FreeSync 5 ms 75 Hz 29 po de LG (29WP60G-B) - Noir",
        "shortDescription": "Le moniteur de jeu IPS de 29 po de LG vous en mettra plein la vue avec ses images à couper le souffle. Avec son écran DEL IPS qui offre une meilleure résolution que la HD intégrale, il affiche des images cristallines qui vous laisseront bouche bée. La prise en charge FreeSync avec taux de rafraîchissement de 75 Hz et la réduction du flou de mouvement produisent des mouvements très fluides dans tous vos jeux.",
        "customerRating": 4.56,
        "customerRatingCount": 36,
        "customerReviewCount": 36,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-del-ips-hd-integrale-gtg-freesync-5-ms-75-hz-29-po-de-lg-29wp60g-b-noir/15445751",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 319.99,
        "salePrice": 259.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/154/15445/15445751.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-de-jeu-del-ips-hd-integrale-gtg-freesync-5-ms-75-hz-29-po-de-lg-29wp60g-b-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/154/15445/15445751.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": true,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "13359106",
        "name": "Moniteur jeu FreeSync DEL IPS FHD 60 Hz 24 po d'ASUS/ temps réponse 5 ms gris-gris (VZ249HE) - Noir",
        "shortDescription": "Le moniteur de jeu FreeSync d'ASUS propulsera votre expérience de jeu à un niveau supérieur. La résolution HD intégrale donne vie aux images, tandis que le temps de réponse vidéo de 1 ms produit des images fluides et sans décalage. La technologie Eyecare d'ASUS réduit le scintillement et vous protège contre la lumière bleue nocive pour éviter la fatigue oculaire, même durant les marathons de jeu.",
        "customerRating": 3.61,
        "customerRatingCount": 56,
        "customerReviewCount": 56,
        "productUrl": "/fr-ca/produit/moniteur-jeu-freesync-del-ips-fhd-60-hz-24-po-d-asus-temps-reponse-5-ms-gris-gris-vz249he-noir/13359106",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 179.99,
        "salePrice": 179.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/133/13359/13359106.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-jeu-freesync-del-ips-fhd-60-hz-24-po-d-asus-temps-reponse-5-ms-gris-gris-vz249he-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/133/13359/13359106.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "16373366",
        "name": "Moniteur de jeu FreeSync ACL VA UHD 4K 165 Hz de 55 po Odyssey Ark de Samsung avec temps de réponse de 1 ms gris à gris (LS55BG970NNXGO)",
        "shortDescription": "Donnez vie à votre jeu avec le moniteur de jeu FreeSync ACL Ultra HD 4K Odyssey Ark de 55 po de Samsung. Doté de technologies avancées, il offre une luminosité parfaitement contrôlée, un contraste précis, des couleurs authentiques et des mouvements incroyablement fluides. Il est également équipé du mode Cockpit et de l'éclairage Eclipse pour vous offrir une toute nouvelle perspective, pour une expérience complètement immersive.",
        "customerRating": 4.53,
        "customerRatingCount": 15,
        "customerReviewCount": 15,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-freesync-acl-va-uhd-4k-165-hz-de-55-po-odyssey-ark-de-samsung-avec-temps-de-reponse-de-1-ms-gris-a-gris-ls55bg970nnxgo/16373366",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 3999.99,
        "salePrice": 3999.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/163/16373/16373366.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 14.0,
        "seoText": "moniteur-de-jeu-freesync-acl-va-uhd-4k-165-hz-de-55-po-odyssey-ark-de-samsung-avec-temps-de-reponse-de-1-ms-gris-a-gris-ls55bg970nnxgo",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/163/16373/16373366.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "15529863",
        "name": "Moniteur de jeu HD intégrale DEL IPS FreeSync 144 Hz 4 ms g.-g. de 27 po Optix de MSI (G272) - Noir",
        "shortDescription": "Conquérez les mondes de vos jeux comme jamais auparavant avec ce moniteur de jeu FreeSync Optix de MSI. Son écran DEL IPS de 27 po offre une résolution HD intégrale 1080p, un rapport de contraste statique de 1000:1 et une luminosité de 250 cd/m2 pour afficher des images réalistes avec des détails précis. Avec 2 ports HDMI et 1 port DisplayPort, vous pouvez jumeler une variété de périphériques pris en charge.",
        "customerRating": 4.75,
        "customerRatingCount": 8,
        "customerReviewCount": 8,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-hd-integrale-del-ips-freesync-144-hz-4-ms-g-g-de-27-po-optix-de-msi-g272-noir/15529863",
        "currentRegion": null,
        "hideSavings": true,
        "hideSaleEndDate": true,
        "productType": null,
        "regularPrice": 289.99,
        "salePrice": 289.99,
        "saleEndDate": null,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/155/15529/15529863.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-de-jeu-hd-integrale-del-ips-freesync-144-hz-4-ms-g-g-de-27-po-optix-de-msi-g272-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/images/common/pictures/noimage1500x1500.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": false,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "12874669",
        "name": "Moniteur de jeu DEL TN HD intégrale FreeSync 1 ms gris à gris 75 Hz 21,5 po d'ASUS (VP228QG) - Noir",
        "shortDescription": "Profitez d'une expérience de jeu rehaussée avec ce moniteur de jeu FreeSync de 21,5 po d'ASUS. La résolution HD intégrale offre des jeux et des films en toute clarté, tandis que le temps de réponse de 1 ms produit des images fluides et sans décalage. La technologie Eye Care d'ASUS réduit le scintillement et protège vos yeux contre les émissions de lumière bleue nocives.",
        "customerRating": 3.97,
        "customerRatingCount": 63,
        "customerReviewCount": 63,
        "productUrl": "/fr-ca/produit/moniteur-de-jeu-del-tn-hd-integrale-freesync-1-ms-gris-a-gris-75-hz-21-5-po-d-asus-vp228qg-noir/12874669",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 179.99,
        "salePrice": 139.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/128/12874/12874669.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 4.0,
        "seoText": "moniteur-de-jeu-del-tn-hd-integrale-freesync-1-ms-gris-a-gris-75-hz-21-5-po-d-asus-vp228qg-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/images/common/pictures/noimage1500x1500.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": true,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    },
    {
        "sku": "14897502",
        "name": "Moniteur jeu FreeSync UHD 4K DEL VA HDR 4 ms GTG 60 Hz 31,5 po de LG (32UN500-W) - Noir",
        "shortDescription": "Retrouvez-vous au coeur d'un contenu visuel intense avec ce moniteur de jeu de LG. Ce puissant appareil DEL de 32 po offre une résolution UHD 4K incroyable avec une précision de couleurs optimale et une reproduction des images aisée. Grâce à la fonction Dynamic Action Sync, vous profiterez d'actions, de personnages et de mouvements qui bougent rapidement, avec moins de latence.",
        "customerRating": 4.18,
        "customerRatingCount": 170,
        "customerReviewCount": 170,
        "productUrl": "/fr-ca/produit/moniteur-jeu-freesync-uhd-4k-del-va-hdr-4-ms-gtg-60-hz-31-5-po-de-lg-32un500-w-noir/14897502",
        "currentRegion": null,
        "hideSavings": false,
        "hideSaleEndDate": false,
        "productType": null,
        "regularPrice": 549.99,
        "salePrice": 399.99,
        "saleEndDate": 1665125999000,
        "thumbnailImage": "https://multimedia.bbycastatic.ca/multimedia/products/150x150/148/14897/14897502.jpg",
        "primaryParentCategoryId": null,
        "categoryName": "Moniteurs de jeu",
        "ehf": 6.0,
        "seoText": "moniteur-jeu-freesync-uhd-4k-del-va-hdr-4-ms-gtg-60-hz-31-5-po-de-lg-32un500-w-noir",
        "sellerId": null,
        "seller": null,
        "highResImage": "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/148/14897/14897502.jpg",
        "altLangSeoText": null,
        "offerId": null,
        "priceUnit": "",
        "requiresAgeVerification": false,
        "isPriceEndsLabel": false,
        "hasPromotion": true,
        "isAdvertised": false,
        "isClearance": false,
        "isInStoreOnly": false,
        "isOnlineOnly": false,
        "isVisible": true,
        "isPreorderable": false,
        "isFrenchCompliant": true,
        "isMarketplace": false,
        "hasFrenchContent": false,
        "categoryIds": [
            "20001",
            "20367",
            "474835"
        ]
    }
];